export const environment = {
    t2y12PruGU9wUtEGzBJfolMIgK:"CAR:F-PAY:F-ANA:F-ACT:F-APP:F",
    version: require('../../package.json').version,
    production: false,
    remoteConfig: true,
    remoteConfigUrl: './chat-config.json',
    remoteContactsUrl: '',
    chatEngine: 'mqtt',
    uploadEngine: 'native',
    pushEngine: 'none',
    fileUploadAccept: "*/*",
    firebaseConfig: {
        tenant: 'CHANGEIT',
        apiKey: 'pre-CHANGEIT',
        authDomain: 'CHANGEIT',
        databaseURL: 'CHANGEIT',
        projectId: 'CHANGEIT',
        storageBucket: 'CHANGEIT',
        messagingSenderId: 'CHANGEIT',
        appId: 'CHANGEIT',
        chat21ApiUrl: 'CHANGEIT',
        vapidKey: 'CHANGEIT'
    },
    chat21Config: {
        appId: 'CHANGEIT',
        MQTTendpoint: 'CHANGEIT', // MQTT endpoint
        APIendpoint: 'CHANGEIT'
    },
    apiUrl: 'CHANGEIT',
    whatsappTemplatesBaseUrl: 'CHANGEIT',
    baseImageUrl: 'CHANGEIT',
    dashboardUrl: 'CHANGEIT',
    widgetBaseUrl:'CHANGEIT',
    wsUrl: 'CHANGEIT',
    wsUrlRel: 'CHANGEIT',
    storage_prefix: 'chat_sv5',
    authPersistence: 'LOCAL',
    logLevel: 'Info',
    supportMode: false,
    archivedButton: false,
    writeToButton: false,
    emailSection: true,
    whatsappTemplatesSection: true,
    googleMapsApiKey:"CHANGEIT"
};
